### ISSUE TITLE
Words get removed from the options list when searching for the same word twice

### ISSUE THREAD

**Issue by bworwa** [selectize/selectize.js#1299]
When searching for the same word twice (it also works for single letters or substrs) they get removed from the options list.

Steps to reproduce:

1. Have an option labeled "Lorem ipsum"
2. Search "Lorem lorem" or "rem rem" or "sum sum", etc.

Expected result:

The word "Lorem" should be highlighted in the options, no matter how many times the word is typed. The option label should never be changed from its original value.

Actual result:

The word "lorem" gets removed from the option and it doesn't get reset when closing the select. The original option label gets altered and words start to get missing. It all becomes a mess.

**Comment by piperone** [comment]
![doedoe](https://user-images.githubusercontent.com/351744/27007153-5d78e6e0-4e49-11e7-98cc-3045edc9f687.gif)

[Fiddle](http://jsfiddle.net/a06dLhuw/1/)

The bug affects the latest versions of Chrome, Safari and Firefox.

Given the popularity of Selectize, it is surprising to say the least if this bug has been present since the last release in October.

**Comment by mvdam** [comment]
I just found out that this bug is already fixed. See https://github.com/selectize/selectize.js/pull/1193. Unfortunately it isn't released yet. It seems like its planned for v0.12.5.

**Comment by batjaa** [comment]
When is v0.12.5 release scheduled?

**Comment by piperone** [comment]
> When is v0.12.5 release scheduled?

At this rate, I'm starting to wonder whether it ever will be. The bug is still present and the latest release was in October 2016. This project truly is dead now, isn't it? :-(

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
