### ISSUE TITLE
Handle 'input' event.

### ISSUE THREAD

**Issue by marcandre** [selectize/selectize.js#1462]
Welcome to the Selectize bug tracker. Thank you for taking the time to
make Selectize a better library!

Please keep in mind this repository has an important issue backlog and
that maintainers have limited time to fix issues, triage, and understand
them.

If you've never done so, please read the
[guide to reporting issues](https://github.com/selectize/selectize.js/wiki/Reporting-issues-guide)
in the Wiki to help us better understand your issue.

Place an `x` in the checklist steps (`[ ]` becomes `[x]`) to demonstrate
you have done/verified all the steps you needed to do.

Thank you for reading this! You can now erase everything up to the
following dashes, and then complete what's after.

ISSUES THAT EITHER:

* IGNORE THE ISSUE GUIDELINES
* ERASE THE FOLLOWING TEMPLATE
* DON'T FOLLOW THE PROPER NUMBERED FORMAT FOR STEPS TO REPRODUCE

COULD BE CLOSED.

---

I did:

* [x] Search for if my issue has already been submitted
* [x] Make sure I'm reporting something precise that needs to be fixed
* [x] Give my issue a descriptive and concise title
* [x] Create a *minimal* working example on JsFiddle or Codepen
	(or gave a link to a demo on the Selectize docs)
* [x] Indicate *precise* steps to reproduce in *numbers* and the result,
	  like below

**Bug**: While not widely known, the `input` event is triggered before all `change` events for inputs and selects (see [the spec here](https://www.w3.org/TR/html5/forms.html#send-select-update-notifications))

Steps to reproduce:

1. Go to https://codepen.io/marcandre/pen/vQjPxM?editors=1010#0
2. Select any item
3. Notice there is no alert

Expected result: It should alert "Hello"

Actual result: It doesn't

I'm opening an issue instead of producing a PR because of the huge list of open PRs. As a maintainer I understand how busy one can be, but I also don't want to waste my time. I'll produce a good PR on the promise it will get merged.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.

**Comment by doomedramen** [comment]
I am still having this issue.

**Comment by marcandre** [comment]
This has been fixed in v0.13.1+

**Comment by doomedramen** [comment]
hmm, I still have this issue with 0.13.1 (*.2 and *.3) but maybe I have a non-ordenary setup, as soon as I remove the .selectize call from my <select> validation works, I will continue trying to diagnose and report back.
