### ISSUE TITLE
Required fields can not be focusable

### ISSUE THREAD

**Issue by oswaldoacauan** [selectize/selectize.js#733]
Error: `An invalid form control with name=''" is not focusable.`
File: `/examples/required.html`
Browsers: `Chrome v40` and `Chrome Canary v43`
SO: `Windows 7`

Ref.: #63 and #136

Seems that the issue is back :sweat_smile:

**Comment by scaytrase** [comment]
Confirm, required inputs become hidden and unfocusable (which leads to submit fail). Also I cannot make the selectized input required.

**Comment by conarwelsh** [comment]
same here 
![image](https://cloud.githubusercontent.com/assets/2643188/6716169/20101cfa-cd69-11e4-8a49-178ead73d7a1.png)

**Comment by therocode** [comment]
Also experiencing this

**Comment by rudymacias** [comment]
Same here.

**Comment by seanodotcom** [comment]
Seeing this in Chrome 42 as well.

**Comment by chibicode** [comment]
Same here on Chrome 43.

**Comment by Alex-Sokolov** [comment]
Some sort of workaround...

Let style invalid selects with red border

``` css
.selectize-control.invalid > .selectize-input {
    border-color: red;
}
```

And in init of each select add code for checking validation

``` js
$('select').each(function() {
    var $select = $(this).selectize(options);
    selectizeValidationFix($select);
});

function selectizeValidationFix($select) {

    var self = $select[0].selectize;

    self.$input.on('invalid', function (event) {
        event.preventDefault();
        self.focus(true);
        self.$wrapper.addClass('invalid');
    });

    self.$input.on('change', function (event) {
        if (event.target.validity && event.target.validity.valid) {
            self.$wrapper.removeClass('invalid');
        }
    });

}
```

Result: no error message in console about "not focusable" and styling invalid selects with red border. But if on page few selects - all opened together

**Comment by dexcell** [comment]
Yeah, hopefully this bug is going to fixed soon.

I did a quick dirty fix since i also need it. At least it worked for me.
On selectize.js (un-minified) line 2655.

Change the code from

```
self.$control_input.prop('required', invalid);
```

 to 

```
self.$control_input.prop('required', self.$input.val() == '');
self.$input.prop('required', false);
```

Use at your own risk. Only tested aganist dropdown style of selectizejs.
Hopefully it help someone.

**Comment by oswaldoacauan** [comment]
@brianreavis any thoughts on this?

**Comment by sintro** [comment]
Same problem, "is not focusable" problem is still here

**Comment by bogdancss** [comment]
any updates on this?

**Comment by joallard** [comment]
It's not being actively worked on. A PR with tests is most welcome, and '+1' votes (not comments) help determine what's a priority.

**Comment by joallard** [comment]
I can't repro this in Chrome 52 (Mac). Is this still happening?

**Comment by kmarcisz** [comment]
This is still an issue. Just tried the `examples/required.html` on a Mac in Chrome 52, getting the `An invalid form control with name='' is not focusable.` error.

**Comment by joallard** [comment]
Getting the error just loading the page? I'm definitely not getting that. It loads without any error.

**Comment by oswaldoacauan** [comment]
I think you need to submit the form.

**Comment by joallard** [comment]
We got a winner!

### STR
1. In Chrome (using v51), go to `examples/required.html`
2. Using the "Required element" example, make sure no option is selected
3. Click Submit

Actual: Thrown "An invalid form control with name='' is not focusable."
Expected: No exception; browser indicates empty field error.

**Comment by joallard** [comment]
A fix is committed, would someone confirm?

**Comment by kmarcisz** [comment]
Bug still present on the master branch. Same error, trying to submit an empty form in `examples/required.html` throws the same exception in console.

**Comment by joallard** [comment]
@kmarcisz Are you sure you're running the code in `src/selectize.js` and running the above STR? Because running STR in Chrome 52 doesn't return reported behavior for me.

**Comment by fgagne** [comment]
@joallard the fix is working on Chrome 52.0.2743.116 m (64-bit) on Windows 10.

I've build the master branch and I don't get the error.
I've build the 0.12.2 tag, I do get the error.

Thanks for fixing this.
