### ISSUE TITLE
Question: how to refresh options list on each call to remote data source?

### ISSUE THREAD

**Issue by u01jmg3** [selectize/selectize.js#907]
Each call to my remote data source requires a new search. However, selectize always wants to cache past options. The reason I don't need this behaviour is each option chosen by the user reduces the results returned by the remote server so caching the options is not necessary as options previously returned may no longer be valid.

How do I always refresh the cache / options array with the results of any new search the user formulates?

I have tried: `$select[0].selectize.clearCache('options');`

Here is my code so far

``` js
var $select = $('.autocomplete').selectize({
    valueField: 'suggestion',
    labelField: 'suggestion',
    searchField: 'suggestion',
    closeAfterSelect: true,
    create: false,
    render: {
        option: function(item, escape){
            return '<div>' + item.suggestion + '</div>';
        }
    },
    load: function(query, callback){
        if(!query.length)
            return callback();

        query = encodeURIComponent(query);
        var items = $select[0].selectize.items;
        if(items.length > 0){
            items = items.map(encodeURIComponent);
            query += '/' + items.join('/');
        }

        $.ajax({
            url: '{{URL::to('/')}}/search/postgraduate/programmes/suggestions/' + query,
            type: 'GET',
            error: function(){
                callback();
            },
            success: function(res){
                callback(res.suggestions);
            }
        });
    }
});
```

**Comment by u01jmg3** [comment]
Fixed by calling `this.clearOptions();` in `onItemAdd` although I see Selectize also calls `self.clear();` but I want to keep the existing items I have selected.

**Comment by u01jmg3** [comment]
Relates to #449

**Comment by TahseenAlaa** [comment]
I got the same issue but not solved when using `this.clearOptions();`
any way to solve this issue ?
